server:
  servlet:
    context-path: /marketplace
spring:
  datasource:
    username: root
    password: ':A2y,ZGjE3YrN6c%'
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/marketplace?useUnicode=TRUE&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=FALSE
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  banner:
    location: "classpath:custom-banner.txt"
  liquibase:
#    changeLogFile: classpath:dbchangelog.xml
    change-log: classpath:dbchangelog.xml
    dropFirst: false
    enabled: true